---
title: "APR Manufacturing PMI Analysis"
output: html_document
author: Hilary Lai
---

## Setting up AP PMI Data by Month

```{r setup, include=T, warning=F, message=F}
library(tidyverse)
library(readr)
library(ggplot2)
library(forecast)
library(tidyr)

pmi <- read_csv("pmi.csv")
#find ap
pmi.ap <- pmi[,c(1,2,5,7,9)]
pmi.ap$Release_Date <- mdy(pmi.ap$Release_Date)
ap.ts <- ts(pmi.ap[,(c(2:5))], frequency=12, start=c(2016,3.5))
autoplot(ap.ts)
```

## AP PMI Regional Mean (ASEAN, TW, IN, KR)
```{r plot.ap, include=T, warning=F, message=F}
pmi.ap.total <- pmi.ap %>%
  mutate(PMI = (ASEAN+India+Korea+Taiwan)/4) %>% .[,c(1,6)]
ap.ts.total <- ts(pmi.ap.total[,2], frequency=12, start=c(2016,3.5))
plot.pmi <- autoplot(ap.ts.total) +
  ylab("PMI") + xlab("Calendar Mth")
```

## Fitting ARIMA Forecast
```{r arima.fc, include=T, warning=F, message=F}
fit <- auto.arima(ts(ap.ts.total, frequency=12, start=c(2016,3.5)))
fc <- forecast(fit, h=20)
summary(fc)
```

### As shown, the model has a low MPE, which is good for forecasting

```{r fit.plot, include=T, warning=F, message=F}
autoplot(forecast(fit, h=20)) + geom_line(size=1) +
  ylab("PMI") + xlab("Calendar Mth")
```